/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ReviewsReviewIdRouteImport } from './routes/reviews.$reviewId'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as OrderSuccessIdRouteImport } from './routes/order-success.$id'
import { Route as FixProblemProblemIdRouteImport } from './routes/fix-problem.$problemId'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as AccountSettingsRouteImport } from './routes/account_.settings'
import { Route as ReviewOrderIdProductIdRouteImport } from './routes/review.$orderId.$productId'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AdminStockProductIdRouteImport } from './routes/admin_.stock.$productId'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AdminOrdersOrderIdProblemRouteImport } from './routes/admin_.orders.$orderId.problem'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsReviewIdRoute = ReviewsReviewIdRouteImport.update({
  id: '/reviews/$reviewId',
  path: '/reviews/$reviewId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessIdRoute = OrderSuccessIdRouteImport.update({
  id: '/order-success/$id',
  path: '/order-success/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FixProblemProblemIdRoute = FixProblemProblemIdRouteImport.update({
  id: '/fix-problem/$problemId',
  path: '/fix-problem/$problemId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/account_/settings',
  path: '/account/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewOrderIdProductIdRoute = ReviewOrderIdProductIdRouteImport.update({
  id: '/review/$orderId/$productId',
  path: '/review/$orderId/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStockProductIdRoute = AdminStockProductIdRouteImport.update({
  id: '/admin_/stock/$productId',
  path: '/admin/stock/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminOrdersOrderIdProblemRoute =
  AdminOrdersOrderIdProblemRouteImport.update({
    id: '/admin_/orders/$orderId/problem',
    path: '/admin/orders/$orderId/problem',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/account/settings': typeof AccountSettingsRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/fix-problem/$problemId': typeof FixProblemProblemIdRoute
  '/order-success/$id': typeof OrderSuccessIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/reviews/$reviewId': typeof ReviewsReviewIdRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/stock/$productId': typeof AdminStockProductIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/review/$orderId/$productId': typeof ReviewOrderIdProductIdRoute
  '/admin/orders/$orderId/problem': typeof AdminOrdersOrderIdProblemRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/account/settings': typeof AccountSettingsRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/fix-problem/$problemId': typeof FixProblemProblemIdRoute
  '/order-success/$id': typeof OrderSuccessIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/reviews/$reviewId': typeof ReviewsReviewIdRoute
  '/products': typeof ProductsIndexRoute
  '/admin/stock/$productId': typeof AdminStockProductIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/review/$orderId/$productId': typeof ReviewOrderIdProductIdRoute
  '/admin/orders/$orderId/problem': typeof AdminOrdersOrderIdProblemRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/account_/settings': typeof AccountSettingsRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/fix-problem/$problemId': typeof FixProblemProblemIdRoute
  '/order-success/$id': typeof OrderSuccessIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/reviews/$reviewId': typeof ReviewsReviewIdRoute
  '/products/': typeof ProductsIndexRoute
  '/admin_/stock/$productId': typeof AdminStockProductIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/review/$orderId/$productId': typeof ReviewOrderIdProductIdRoute
  '/admin_/orders/$orderId/problem': typeof AdminOrdersOrderIdProblemRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/account/settings'
    | '/collections/$slug'
    | '/email/unsubscribe'
    | '/fix-problem/$problemId'
    | '/order-success/$id'
    | '/products/$slug'
    | '/reviews/$reviewId'
    | '/products/'
    | '/admin/stock/$productId'
    | '/lovable/email/suppression'
    | '/review/$orderId/$productId'
    | '/admin/orders/$orderId/problem'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/account/settings'
    | '/collections/$slug'
    | '/email/unsubscribe'
    | '/fix-problem/$problemId'
    | '/order-success/$id'
    | '/products/$slug'
    | '/reviews/$reviewId'
    | '/products'
    | '/admin/stock/$productId'
    | '/lovable/email/suppression'
    | '/review/$orderId/$productId'
    | '/admin/orders/$orderId/problem'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/account_/settings'
    | '/collections/$slug'
    | '/email/unsubscribe'
    | '/fix-problem/$problemId'
    | '/order-success/$id'
    | '/products/$slug'
    | '/reviews/$reviewId'
    | '/products/'
    | '/admin_/stock/$productId'
    | '/lovable/email/suppression'
    | '/review/$orderId/$productId'
    | '/admin_/orders/$orderId/problem'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  FixProblemProblemIdRoute: typeof FixProblemProblemIdRoute
  OrderSuccessIdRoute: typeof OrderSuccessIdRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ReviewsReviewIdRoute: typeof ReviewsReviewIdRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  AdminStockProductIdRoute: typeof AdminStockProductIdRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ReviewOrderIdProductIdRoute: typeof ReviewOrderIdProductIdRoute
  AdminOrdersOrderIdProblemRoute: typeof AdminOrdersOrderIdProblemRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/$reviewId': {
      id: '/reviews/$reviewId'
      path: '/reviews/$reviewId'
      fullPath: '/reviews/$reviewId'
      preLoaderRoute: typeof ReviewsReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success/$id': {
      id: '/order-success/$id'
      path: '/order-success/$id'
      fullPath: '/order-success/$id'
      preLoaderRoute: typeof OrderSuccessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fix-problem/$problemId': {
      id: '/fix-problem/$problemId'
      path: '/fix-problem/$problemId'
      fullPath: '/fix-problem/$problemId'
      preLoaderRoute: typeof FixProblemProblemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/settings': {
      id: '/account_/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$orderId/$productId': {
      id: '/review/$orderId/$productId'
      path: '/review/$orderId/$productId'
      fullPath: '/review/$orderId/$productId'
      preLoaderRoute: typeof ReviewOrderIdProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/stock/$productId': {
      id: '/admin_/stock/$productId'
      path: '/admin/stock/$productId'
      fullPath: '/admin/stock/$productId'
      preLoaderRoute: typeof AdminStockProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/orders/$orderId/problem': {
      id: '/admin_/orders/$orderId/problem'
      path: '/admin/orders/$orderId/problem'
      fullPath: '/admin/orders/$orderId/problem'
      preLoaderRoute: typeof AdminOrdersOrderIdProblemRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  FixProblemProblemIdRoute: FixProblemProblemIdRoute,
  OrderSuccessIdRoute: OrderSuccessIdRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ReviewsReviewIdRoute: ReviewsReviewIdRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  AdminStockProductIdRoute: AdminStockProductIdRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ReviewOrderIdProductIdRoute: ReviewOrderIdProductIdRoute,
  AdminOrdersOrderIdProblemRoute: AdminOrdersOrderIdProblemRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
